/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 desktop.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/desktop-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={materials.Metal} />
      <group position={[0.86, 2.98, 0]}>
        <mesh geometry={nodes.Plane001_1.geometry} material={materials.Metal} />
        <mesh geometry={nodes.Plane001_2.geometry} material={materials['Front Screen']} />
      </group>
    </group>
  )
}

useGLTF.preload('/desktop-transformed.glb')
